server:
  port: 8092

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/danggeun
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : true
    open-in-view: false
    show-sql: true